### ISSUE TITLE
Compiling the Test Application

### ISSUE THREAD

**Issue by imbur** [kevoree/xp-models15#1]
Hi,
I am trying to re-run the evaluation presented in your MODELS 2015 paper locally on my machine. However, instead of a successful build, I get a maven compile error saying "long cannot be dereferenced" (see maven output at the bottom of this issue).

To reproduce
(1) clone the repo
(2) modify the `kmf.version` in `pom.xml` at the root of the repo as shown [here](https://github.com/imbur/xp-models15/commit/bf61fad63fa616679209c9e5343eb8e77e52bfad) 
(3) build the application in the repository root with `mvn clean install -X`

Thank you for your help in advance!

maven output:
```
[...]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] ~/git/xp-models15/org.kevoree.proto.models15.server/src/main/java/org/kevoree/proto/models15/server/TEST2_Server.java:[105,47] long cannot be dereferenced
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.kevoree.proto.models15.root .................... SUCCESS [  0.272 s]
[INFO] org.kevoree.proto.models15.model ................... SUCCESS [  1.965 s]
[INFO] org.kevoree.proto.models15.server .................. FAILURE [  0.235 s]
[INFO] org.kevoree.proto.models15.client .................. SKIPPED
[INFO] org.kevoree.proto.models15.runner .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.591 s
[INFO] Finished at: 2018-06-15T21:59:17-04:00
[INFO] Final Memory: 25M/619M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project org.kevoree.proto.models15.server: Compilation failure
[ERROR] ~/git/xp-models15/org.kevoree.proto.models15.server/src/main/java/org/kevoree/proto/models15/server/TEST2_Server.java:[105,47] long cannot be dereferenced
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.kevoree.proto.models15.server
```

**Comment by dukeboard** [comment]
Hi,
Sorry for the inconvenience, this snapshot version was not released immediately.
I slightly upgraded the code to make this compatible without deep test about consistency of results.
Also be aware that KMF was continuously updated since 2015 so these results has been highly improve within the following version and also in the spin-off project named GreyCat. Don't hesitate to come back to me if this quick fix does not match expectation.

**Comment by imbur** [comment]
Hi,
Thank you for the quick response! Where are the modifications you mention visible?
Additionally, if I wanted to run the evaluation scenario included in the MODELS'15 paper with the most up-to-date tool, how should I get started then?
Thank you,
Marton

**Comment by dukeboard** [comment]
Hi, 
I finally pushed the quick fix on the master branch so feel free to checkout to test again.
After the model paper we investigated more the async model and a new model serialisation format. Due to these reasons we started the GreyCat project fully asynchronous, with a binary model format.
You can find the documentation here: https://greycat.io/ which contains link to Github and minimal documentation. Feel free to have a look and don't hesitate to come back to me if you are interested to use it in a benchmark. Best Regards.

**Comment by imbur** [comment]
Hi,
Thank you very much! It is building fine now. Closing the issue.
